version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name N-HANDSON --s3-location s3://n-handson-ope/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src